name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Esto puede quedar aunque estés en Windows, ya que se ejecuta en los servidores de GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
